flowchart LR
  subgraph IN["accounts: overdraft_usage"]
    in_accountNumber["accountNumber"]
    in_sentDate["sentDate"]
    in_overdraftLimit["overdraftLimit"]
    in_overdraftUsed["overdraftUsed"]
  end
  subgraph OUT["credit: loan_application_data"]
    out_loan_applications___application_id["loan_applications[].application_id"]
    out_loan_applications___timestamp["loan_applications[].timestamp"]
    out_loan_applications___applicant_customer_id["loan_applications[].applicant.customer_id"]
    out_loan_applications___loan_details_requested_amount["loan_applications[].loan_details.requested_amount"]
    out_loan_applications___financial_profile_total_assets["loan_applications[].financial_profile.total_assets"]
  end
  in_accountNumber -->|EXACT| out_loan_applications___application_id
  in_sentDate -->|RENAMED| out_loan_applications___timestamp
  in_accountNumber -->|SEMANTIC| out_loan_applications___applicant_customer_id
  in_overdraftLimit -->|MERGE| out_loan_applications___loan_details_requested_amount
  in_overdraftUsed -->|MERGE| out_loan_applications___loan_details_requested_amount
  in_overdraftLimit -->|SEMANTIC| out_loan_applications___financial_profile_total_assets
  in_overdraftUsed -->|SEMANTIC| out_loan_applications___financial_profile_total_assets